"""Add password field to mechanic

Revision ID: 58587ff1a4ea
Revises: 
Create Date: 2025-08-04 13:50:53.513974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58587ff1a4ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
